version: '3.7'

services:
    php:
        user: "${UID}:${GID}"
        container_name: php
        env_file:
            - ./.env
        build:
          context: ./docker/php
        volumes:
          - .:/var/www/gesco:rw,cached
        depends_on:
          - postgres

    nginx:
        image: nginx:1.19.0
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./public:/var/www/gesco/public:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    # db:
    #     # This image exposes the standard MySQL port (3306)
    #     image: mysql:8.0
    #     container_name: mysql
    #     command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    #     ports:
    #         - 3307:3306
    #     volumes:
    #         - ./db-data:/var/lib/mysql/data
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=gesco
    #         - MYSQL_DATABASE=gesco
    #         - MYSQL_USER=gesco
    #         - MYSQL_PASSWORD=gesco
    #     restart: always

    postgres:
        image: postgres:12
        container_name: gesco_psql
        environment:
            - POSTGRES_USER=gesco
            - POSTGRES_PASSWORD=gesco
            - POSTGRES_DB=gesco
            - PGDATA=/var/lib/postgresql/data/db-files/
            - /etc/localtime:/etc/localtime:ro
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: always

    adminer:
        image: adminer:latest
        container_name: gesco_adminer
        restart: always
        depends_on:
            - postgres
        ports:
            - 8081:8080

volumes:
    db-data:
        driver: local
    # search-data:
    #   driver: local