<?php declare(strict_types=1);

namespace Gesco\Helper;

use League\Csv\Reader;

class ActivityHelper
{
    public static function getActivities()
    {
        return [
            "Agence de location",
            "Agence de transfert d'argent",
            "Agence de voyage",
            "Alimentation générale",
            "Atelier de coiffure",
            "Atelier de couture",
            "Atelier de couture",
            "Bar Dancing",
            "Bijouterie",
            "Boîte de nuit",
            "Boucherie",
            "Boucherie Petit Modèle",
            "Boulangerie",
            "Boulangerie-Pâtisserie",
            "Briqueterie",
            "Cabinet comptable juridique et fiscal",
            "Cabinet d'avocat",
            "Cabinet médical",
            "Cafétéria",
            "Clinique",
            "Commerce Electro-ménager",
            "Compagnie d'assurance",
            "Cybercafé",
            "Ecole Primaire",
            "Ecole Secondaire",
            "Ecole Supérieure",
            "Epicerie",
            "Etablissement de communication",
            "Fleuriste",
            "Garage",
            "Horlogerie ",
            "Hôtel",
            "Imprimerie",
            "Jardin d'enfants",
            "Librairie",
            "Maison close",
            "Maroquinerie",
            "Menuiserie",
            "Motel",
            "Pâtisserie",
            "Pharmacie",
            "Poissonnerie petit modèle",
            "Pompe funèbre",
            "Prêt-à-porter",
            "Prêt-à-porter enfants",
            "Quincaillerie ",
            "Quincaillerie petite modèle",
            "Restaurant",
            "Salle de jeux",
            "Salon de coiffure",
            "salon de thé",
            "Salon d'esthétique",
            "Snack-bar",
            "Société agricole",
            "Société BTP",
            "Société commerciale",
            "Société d'assurance",
            "Société de transport",
            "Société Industrielle",
            "Superette",
            "Vente d’aliments secs",
            "Vente de bazar",
            "Vente de bétail",
            "Vente de bijoux ",
            "Vente de boissons",
            "Vente de friperie",
            "Vente de produits cosmétiques",
            "Vente de produits d’ameublement",
            "Vente de vêtements",
            "Vente de vivres frais",
            "Vente de volailles",
            "Vente en gros et détail alimentation",
            "Vente en gros et détail bazar",
            "Vidéothèque",
            "Vulcanisateur"
        ];
    }
}
